#!/usr/bin/env bash
# Copyright Marc Ketel
# SPDX-License-Identifier: Apache-2.0
#
# Run the ACT test suite for a subset of the PlatformIO environments in the
# emulator's platformio_isa-extension-combination_env.ini.
#
# Usage: test_all.sh --full  [--dry-run] [filter-regex]
#        test_all.sh --smoke [--dry-run] [filter-regex]
#
#   --full    run every environment in the ini.
#   --smoke   run the environments marked "# smoke" in the ini. The generator
#             (generate-isa-extension-combination.py) marks: in default mode
#             every env of the covering array; in --full mode each extension
#             alone plus every maximal legal combination.
#   --dry-run list the selected environments without running them.
#   filter    a regex applied after subset selection, e.g. '^RV32IM'.
#
# EMULATOR_TAG (env var) selects the compiler tag(s): a comma-separated list
# runs the selection once per tag. The default is "gcc,clang"; other tags are
# built via cmake/run-matrix.py, e.g.
#   EMULATOR_TAG=gcc-13 test_all.sh --full '^RV32I'
#
# BACKEND=avr runs the same selection through the simavr backend: each env's
# act-config gets the rve-avr- prefix (generated by gen_core.py with the avr
# backend) and logs land in work/test-all/avr/.
#
# Envs run in parallel, $(nproc) at a time. Each env's run_tests.py also uses
# $(nproc) jobs; there is plenty of memory for the oversubscription.
# The pio build (make build) is serialized with flock so only one compile
# happens at a time. Override both counts with the PARALLEL and JOBS
# environment variables, e.g. PARALLEL=2 JOBS=2 test_all.sh on a low-memory
# machine. Per-env summaries land in work/test-all/<tag>/<env>.log. An env
# counts as done only if its log ends with the run_tests.py success line
# ("RESULT: All N tests passed."); anything else (build failure, test
# failure, interruption) is re-run on the next invocation.

set -u

EMULATOR_SRC_DIR=${EMULATOR_SRC_DIR:-../RISC-V-emulator-Native}
INI="$EMULATOR_SRC_DIR/platformio_isa-extension-combination_env.ini"
# Every ACT step runs inside the container image via scripts/act_container.sh
# (the emulator build stays on the host). Individual emulator tests run for
# milliseconds and use only 16 MiB each, so the nominal PARALLEL x JOBS
# oversubscription never saturates the machine and more parallelism is safe.
PARALLEL=${PARALLEL:-$(nproc)}
JOBS=${JOBS:-$PARALLEL}

BACKEND=${BACKEND:-native}

# Log-directory tag: the avr backend logs under a single avr tag; the native
# backend logs under each selected compiler tag.
tags_for_backend() {
  if [ "$BACKEND" = avr ]; then
    echo avr
  else
    echo "${EMULATOR_TAG:-gcc,clang}" | tr ',' ' '
  fi
}

# Parse flags. --full or --smoke is required; --dry-run is optional.
mode=
dry_run=0
while [ $# -gt 0 ]; do
  case "$1" in
    --full)  mode=full;  shift ;;
    --smoke) mode=smoke; shift ;;
    --dry-run) dry_run=1; shift ;;
    --*) echo "Unknown option: $1" >&2; exit 2 ;;
    *) break ;;
  esac
done
FILTER=${1:-.}

if [ -z "$mode" ]; then
  all=$(grep -oP '^\[env:\K[^\]]+' "$INI" | wc -l)
  smoke=$(grep -c '^# smoke' "$INI")
  cat >&2 <<EOF
Usage: $0 --full  [--dry-run] [filter-regex]
       $0 --smoke [--dry-run] [filter-regex]

  --full    run every environment in the ini ($all envs).
  --smoke   run the environments marked "# smoke" in the ini ($smoke envs):
            each extension alone plus the maximal combinations.
  --dry-run list the selected environments without running them.
  filter    a regex applied after subset selection, e.g. '^RV32IM'.

  EMULATOR_TAG=gcc,clang (default) or a compiler built via
  cmake/run-matrix.py; comma-separated lists run the selection once per tag,
  e.g. EMULATOR_TAG=gcc-13.
EOF
  exit 2
fi

# Select the env list for the chosen mode, then apply the filter regex.
if [ "$mode" = full ]; then
  envs=$(grep -oP '^\[env:\K[^\]]+' "$INI")
else
  # Select envs marked with "# smoke" by the generator script.
  envs=$(awk '
    /^\[env:/ {
      if (env != "" && smoke) print env
      env = $0; sub(/^\[env:/, "", env); sub(/\]$/, "", env); smoke = 0
    }
    /^# smoke/ { smoke = 1 }
    END { if (env != "" && smoke) print env }
  ' "$INI")
fi
envs=$(echo "$envs" | grep -P "$FILTER" || true)
if [ -z "$envs" ]; then
  echo "No environments match filter '$FILTER'." >&2
  exit 2
fi
total=$(echo "$envs" | grep -c .)

run_one() {
  local i=$1 env=$2 config log
  log="$OUTDIR/$env.log"
  if grep -q 'RESULT: All .* tests passed\.' "$log" 2>/dev/null; then
    echo "[$i/$total] $env: skip (passed)"
    return 0
  fi
  config=$(grep -A1 "^\[env:$env\]" "$INI" | grep -oP '^# act-config: \K.+')
  if [ "$BACKEND" = avr ]; then
    config="rve-avr-${config#rve-}"
  fi
  # Serialize the pio compile; the lock is only held for the build.
  if ! flock "$OUTDIR/pio.lock" make build "CONFIG=$config" "EMULATOR_TAG=$EMULATOR_TAG" >> "$log" 2>&1; then
    echo "[$i/$total] $env: BUILD FAILED (see $log)"
    return 1
  fi
  echo "[$i/$total] $env: running"
  if scripts/act_container.sh make elfs run "CONFIG=$config" "JOBS=$JOBS" "EMULATOR_TAG=$EMULATOR_TAG" EMULATOR_SRC_DIR=/emulator >> "$log" 2>&1; then
    echo "[$i/$total] $env: $(tail -1 "$log")"
  else
    echo "[$i/$total] $env: FAILED (see $log)"
  fi
}

if [ "$dry_run" = 1 ]; then
  for tag in $(tags_for_backend); do
    OUTDIR=work/test-all/$tag
    echo "=== Compiler tag: $tag ==="
    i=0
    for env in $envs; do
      i=$((i + 1))
      log="$OUTDIR/$env.log"
      if grep -q 'RESULT: All .* tests passed\.' "$log" 2>/dev/null; then
        echo "[$i/$total] $env: skip (passed)"
      else
        echo "[$i/$total] $env: queued"
      fi
    done
  done
  echo
  echo "Dry run: $total envs selected per tag."
  exit 0
fi

export -f run_one
export INI JOBS total

start=$SECONDS
overall_failed=0
# Comma-separated tags: run the whole selection once per tag. Logs are kept
# per tag in work/test-all/<tag>/.
for tag in $(tags_for_backend); do
  OUTDIR=work/test-all/$tag
  mkdir -p "$OUTDIR"
  export OUTDIR EMULATOR_TAG=$tag
  echo "=== Compiler tag: $tag ==="
  # nl numbers the envs so run_one can print [i/total] progress.
  echo "$envs" | nl -ba | xargs -P "$PARALLEL" -L1 bash -c 'run_one "$@"' _
  failed=$(grep -L 'RESULT: All .* tests passed\.' "$OUTDIR"/*.log 2>/dev/null | wc -l)
  echo "Done tag $tag: $total envs, $failed failed. Logs in $OUTDIR/."
  overall_failed=$((overall_failed + failed))
done

echo
echo "Done in $((SECONDS - start))s."
exit "$overall_failed"
